
import sys
import os
import json
import argparse
from unittest.mock import patch

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.batch_solver import BatchSolver
# WE DO NOT IMPORT VNPTClient here to avoid early binding, we patch it where it is used.

# --- MOCK CLASS ---
class MockVNPTClient:
    def __init__(self, key_file_path='api_keys/api-keys.json'):
        self.request_count = 0
        self.keys = {} 

    def get_embedding(self, text):
        return {"data": [{"embedding": [0.1] * 1024}]}

    def get_request_count(self):
        return self.request_count

    def chat_completion(self, messages, model='vnptai_hackathon_small', **kwargs):
        # Infer QID from prompt if possible
        qid = "mock_qid"
        try:
            content = messages[0]['content']
            import re
            match = re.search(r"<question id='(.*?)'>", content)
            if match:
                qid = match.group(1)
        except:
            pass

        return {
            "content": None,
            "tool_calls": [
                {
                    "id": "call_mock_123",
                    "type": "function",
                    "function": {
                        "name": "submit_batch_results",
                        "arguments": json.dumps({
                            "answers": [
                                {
                                    "id": qid, 
                                    "answer": "A", 
                                    "confidence": 99, 
                                    "reasoning": "MOCK_FULL_TEST: Generated by mock_predict_full.py",
                                    "is_sensitive": False
                                }
                            ]
                        })
                    }
                }
            ]
        }

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    print(f"--- MOCK PREDICT FULL ---")
    print(f"Input: {args.input}")
    print(f"Output: {args.output}")

    # Mock VectorStore search results to bypass DB query
    def mock_search(*args, **kwargs):
        return [
            {"id": "doc_1", "text": "Fake document about Vietnam history.", "metadata": {"source": "wiki"}, "score": 0.9}
        ]

    # Patch modules
    with patch('src.batch_solver.VNPTClient', side_effect=MockVNPTClient), \
         patch('src.retriever.VNPTClient', side_effect=MockVNPTClient), \
         patch('src.vector_store.VectorStore.search', side_effect=mock_search):
        
        solver = BatchSolver()
        import traceback
        try:
            solver.solve(args.input, args.output)
        except Exception:
            traceback.print_exc()
            raise
    
    print("--- MOCK PREDICT DONE ---")

if __name__ == "__main__":
    main()
